version: 2
updates:
  # Maintain dependencies in the Gemfile
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Specify assignees and reviewers
    assignees:
      - "yusukehigasa"
    reviewers:
      - "yusukehigasa"
    # Automatically update dependencies following semantic versioning
    versioning-strategy: auto
    
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    assignees:
      - "yusukehigasa"
